### ISSUE TITLE
Issue on import

### ISSUE THREAD

**Issue by kennymcmillan** [kajchang/world-athletics-api#1]
### Issue Description

I am encountering an issue when attempting to import the `worldathletics` package. The error message is as follows:

TypeError: ForwardRef._evaluate() missing 1 required keyword-only argument: 'recursive_guard' or, 

Pydantic version: 2.8.2
HTTPX version: 0.27.0
Websockets version: 12.0
Error during import: cannot import name 'ModelField' from 'pydantic.fields' 

### Environment

- Python version: 3.12.4
- Pydantic version: 1.10.2 (also tested with 2.8.2)
- HTTPX version: 0.27.0
- Websockets version: 12.0

### Additional Information

I have attempted to use both Pydantic 1.10.2 and 2.8.2, but the issue persists with both versions.

### Request for Assistance

Could you please provide guidance on how to resolve this issue? ;-)

Thank you for your assistance.

**Comment by kaijchang** [comment]
Thanks Kenny! Solved in v1.1.1.
